# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HandleAutolayout' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
platform :ios, '10'
pod 'Log4swift', '1.2.0'
    pod 'SnapKit', '~> 5.6.0'
    pod 'MaterialComponents/TextControls+FilledTextAreas'
    pod 'MaterialComponents/TextControls+FilledTextFields'
    pod 'MaterialComponents/TextControls+OutlinedTextAreas'
    pod 'MaterialComponents/TextControls+OutlinedTextFields'

use_frameworks!
  # Pods for HandleAutolayout

end
