# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMHitachiVantara' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'Nuke', '~> 9.0'
pod 'Toast-Swift', '~> 5.0.0'
  # Pods for MVVMHitachiVantara

end
