# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalTrainApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	

  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'IQKeyboardManagerSwift'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  # Pods for FinalTrainApp

end
