# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'DemoAPIAlamofire1st' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  # Pods for DemoAPIAlamofire1st

end
